---
apiVersion: v2
name: k8s-job
description: A Helm chart to deploy generic Kubernetes jobs with configurable RBAC
type: application
version: 0.1.0
appVersion: "0.1.0"

home: https://github.com/pltf-dev/helm-charts
# icon: https://.svg
keywords:
  - k8s-jobs
  - jobs

maintainers:
  - name: marcel-dias
    email: marcel@pltf.dev
