apiVersion: v2
name: releem-agent
description: Releem agent Helm chart for Kubernetes

type: application
version: 0.2.0

# agent version
appVersion: "1.22.2.1"

home: https://releem.com/

sources:
  - https://github.com/Releem
  - https://github.com/pltf-dev/helm-charts/tree/main/charts/releem-agent

keywords:
  - releem
  - releem-agent

maintainers:
  - name: marcel-dias
    email: marcel@pltf.dev
