{{- range $jobName, $jobConfig := .Values.jobs }}
{{- if $jobConfig.enabled }}
{{- $mergedJson := include "k8s-job.mergeJobConfig" (dict "root" $ "jobName" $jobName "jobConfig" $jobConfig) }}
{{- $merged := $mergedJson | fromJson }}
{{- if and $merged.rbac.create $merged.rbac.rules }}
{{- $fullname := include "k8s-job.jobFullname" (dict "root" $ "jobName" $jobName) }}
---
{{- if $merged.rbac.clusterScope }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullname }}
  annotations:
    argocd.argoproj.io/hook: {{ $merged.argocd.hook }}
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "k8s-job.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullname }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullname }}
    namespace: {{ $.Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  annotations:
    argocd.argoproj.io/hook: {{ $merged.argocd.hook }}
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "k8s-job.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullname }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
