{{- range $jobName, $jobConfig := .Values.jobs }}
{{- if $jobConfig.enabled }}
{{- $mergedJson := include "k8s-job.mergeJobConfig" (dict "root" $ "jobName" $jobName "jobConfig" $jobConfig) }}
{{- $merged := $mergedJson | fromJson }}
{{- if ne (toString $merged.serviceAccount.create) "false" }}
{{- $fullname := include "k8s-job.jobFullname" (dict "root" $ "jobName" $jobName) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}
  annotations:
    argocd.argoproj.io/hook: {{ $merged.argocd.hook }}
    argocd.argoproj.io/sync-wave: "0"
    {{- with $merged.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "k8s-job.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $jobName }}
{{- end }}
{{- end }}
{{- end }}
