{{- $fullname := include "releem-agent.fullname" . }}
{{- $labels := include "releem-agent.labels" . }}
{{- $selectorLabels := include "releem-agent.selectorLabels" . }}
{{- $serviceAccountName := include "releem-agent.serviceAccountName" . }}
{{- $config := .Values.config }}
{{- range $index, $db := .Values.databases }}
{{- if $index }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-{{ $db.name }}
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/database: {{ $db.name }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
      app.kubernetes.io/database: {{ $db.name }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- $labels | nindent 8 }}
        app.kubernetes.io/database: {{ $db.name }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: RELEEM_DEBUG
              value: {{ $db.debug | default $config.debug | quote }}
            - name: RELEEM_ENV
              value: {{ $db.releemEnv | default $config.releemEnv | quote }}
            - name: RELEEM_HOSTNAME
              value: {{ $db.releemHostname | default $config.releemHostname | quote }}
            - name: RELEEM_INTERVAL_GENERATE_CONFIG_SECONDS
              value: {{ $db.intervalGenerateConfigSeconds | default $config.intervalGenerateConfigSeconds | quote }}
            - name: RELEEM_QUERY_OPTIMIZATION
              value: {{ $db.queryOptimization | default $config.queryOptimization | quote }}
            - name: MEMORY_LIMIT
              value: {{ $db.memoryLimit | default $config.memoryLimit | quote }}
            - name: AWS_REGION
              value: {{ $db.awsRegion | default $config.awsRegion | quote }}
            - name: AWS_RDS_PARAMETER_GROUP
              value: {{ $db.awsRdsParameterGroup | default $config.awsRdsParameterGroup | quote }}
            - name: INSTANCE_TYPE
              value: {{ $db.instanceType | default $config.instanceType | quote }}
          {{- if or $.Values.secret.create $.Values.externalSecrets.enabled }}
          envFrom:
            {{- if $.Values.secret.create }}
            - secretRef:
                name: {{ $fullname }}-secret
            {{- end }}
            {{- if $.Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ $fullname }}-es
            {{- end }}
          {{- end }}
          {{- with $.Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
