{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "releem-agent.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.type }}
  target:
    name: {{ include "releem-agent.fullname" . }}-es
  dataFrom: 
{{ .Values.externalSecrets.dataFrom | toYaml | indent 4 }}
{{- end -}}